// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {models} from '../models';

export function GenerateData(arg1:dto.Request):Promise<models.GWAResult>;

export function GetData(arg1:string):Promise<models.GWAResult>;
