// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateData(arg1) {
  return window['go']['main']['App']['GenerateData'](arg1);
}

export function GetData(arg1) {
  return window['go']['main']['App']['GetData'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
