// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateData(arg1) {
  return ObfuscatedCall(0, [arg1]);
}

export function GetData(arg1) {
  return ObfuscatedCall(1, [arg1]);
}
